# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5wVshkSMrXsnCzokPKtceyV1w3Zjvxi
"""

!nvidia-smi

!pip install ultralytics

from ultralytics import YOLO

!yolo task=detect mode=predict model=yolov8l.pt conf=0.25 source='https://ultralytics.com/images/bus.jpg'

!yolo task=detect mode=train model=yolov8l.pt data=/content/drive/MyDrive/data.yaml epochs=50 imgsz=640

